language: c
sudo: false
env:
- ARDUINO_VERSION=1.6.8 ARDUINO_ESP8266_VERSION=2.1.0 ARDUINO_ROOT=${HOME}/arduino-${ARDUINO_VERSION} ARDUINO_ESP8266_ROOT=${ARDUINO_ROOT}/hardware/esp8266com/esp8266 ARDUINO_HOME=${HOME}/Arduino
install:
- cd ${HOME}
- curl -O https://downloads.arduino.cc/arduino-${ARDUINO_VERSION}-linux64.tar.xz
- tar xvf arduino-${ARDUINO_VERSION}-linux64.tar.xz
- git clone --branch ${ARDUINO_ESP8266_VERSION} https://github.com/esp8266/Arduino.git ${ARDUINO_ESP8266_ROOT}
- cd ${ARDUINO_ESP8266_ROOT}/tools && python get.py
- mkdir -p ${ARDUINO_HOME}/libraries
- cd ${ARDUINO_HOME}/libraries && ln -s ${HOME}/firebase-arduino && ln -s ${HOME}/firebase-arduino/src/third-party/arduino-json-5.1.1
script:
- ${ARDUINO_ROOT}/arduino-builder -verbose  -hardware ${ARDUINO_ROOT}/hardware/ -tools ${ARDUINO_ESP8266_ROOT}/tools/ -tools ${ARDUINO_ROOT}/tools-builder/ -fqbn esp8266com:esp8266:nodemcuv2 -libraries ${HOME}/Arduino/libraries/ -prefs build.flash_ld=${ARDUINO_ESP8266_ROOT}/tools/sdk/ld/eagle.flash.4m.ld -prefs build.flash_freq=40 -prefs build.flash_size=4M examples/FirebasePush_ESP8266/FirebasePush_ESP8266.ino
